---
title: "BDA Project"
author: "Niko Miller, Akseli Manninen and Santeri Löppönen"
output: 
  pdf_document: 
    toc: yes
    toc_depth: 3
urlcolor: blue
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(aaltobda)
library(tidyverse)
library(latex2exp)
library(loo)
library(bayesplot)
library(posterior)
library(rstan)

```

\newpage
# 1. Project Description and Motivation

Studying the relationship between income and education has been the focus on many studies, which have 
concluded that there is a strong correlation between higher education and income (Card, 1999). In general, 
individuals with stronger education are more likely to be employed and earn a big salary compared to less 
educated people (Card, 1999). For that reason, education is described as an investment in human capital 
(Wolla & Sullivan, 2017). 

This study examines this phenomenon from the perspective of people that have acquired their education from 
public colleges of the United States. This research is not limited to only considering educational aspects but 
expands it to family backgrounds. As the connection between education and income has been shown in the 
existing literature, this study is more concentrated on the association of the specific features and income.

In this study, a Bayesian approach is taken to observe the bond between the education and family related 
features and earnings. It is in our interest to find out, how accurately the selected features can predict future 
income for the students from public schools. Furthermore, finding the best predictive features amongst the 
vast number of features is pursued. As this study is conducted in a university environment by university 
students, the possible insight would be especially meaningful for the members of the group and peers.

# 2. Data and the analysis problem

Description of the data and the analysis problem. Provide information where the data was obtained, and 
if it has been previously used in some online case study and how your analysis differs from the existing analyses.

# 3. Description of the models

Description of at least two models, for example:
- non hierarchical and hierarchical,
- linear and non linear,
- variable selection with many models.

# 4. Informative or weakly informative priors, and justification of their choices.

# 5. Stan, rstanarm or brms code.

# 6. How to the Stan model was run, that is, what options were used. 
This is also more clear as combination of textual explanation and the actual code line.

# 7. Convergence diagnostics (Rˆ, ESS, divergences) and what was done if the convergence was not good with the first try. 
This should be reported for all models.

# 8. Posterior predictive checks and what was done to improve the model. This should be reported for all models.

# 9. Optional/Bonus: Predictive performance assessment if applicable (e.g. classification accuracy) and evaluation 
of practical usefulness of the accuracy. This should be reported for all models as well.

# 10. Sensitivity analysis with respect to prior choices (i.e. checking whether the result changes a lot if prior 
is changed). This should be reported for all models.

# 11. Discussion of issues and potential improvements.

# 12. Conclusion what was learned from the data analysis.

# 13. Self-reflection of what the group learned while making the project.
 
# 14. References

Insert bibliography here
Card, D. (1999). THE CAUSAL EFFECT OF EDUCATION ON EARNINGS.
Wolla, S. A., & Sullivan, J. (2017). Education, Income, and Wealth. https://fred.stlouisfed.org/graph/?g=7yKu.
